name: Build & Upload Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'
    # Install the gems in the gemfile\
    - name: Setup Environment.
      run: |
        bundle install
    
    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    # Upload only _site/ to FTP server using git-ftp
    - name: Upload site to FTP via git-ftp.
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: ${{ secrets.FTP_LOCATION }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        syncroot: _site/